version: '3.5'
services:
  hive-rest-js:
    build:
      context: ../hive-rest-js
      args:
        APP_MODULE: "hive-io-rest-example"
        APP_SOURCE: "."
        NODE_ENV: "development"
    image: hive-rest-js
    environment:
      CLUSTER_SIZE: 1
      MONGO_URL: "mongodb://mongo:27017/post"
    depends_on:
      - mongo
    command: npm run dev
    ports:
      - 80:3000
    volumes:
      - ../hive-rest-js:/opt/app:rw
      - /opt/app/node_modules
      - ../hive-js-rest-example:/opt/app/node_modules/hive-io-rest-example:rw
      - ../hive-js:/opt/app/node_modules/hive-io-rest-example/node_modules/hive-io:rw
      - ../hive-js:/opt/app/node_modules/hive-io:rw
    networks:
      - hive-io
  mongo:
    image: mongo:3.6.4
    networks:
      - hive-io
    restart: on-failure
  mongo-viewer:
    image: mongo-express:0.44.0
    environment:
      ME_CONFIG_MONGODB_SERVER: "mongo"
      ME_CONFIG_SITE_BASEURL: "/mongo/"
    depends_on:
      - mongo
    ports:
      - 8081:8081
    networks:
      - hive-io
    restart: on-failure

# networking specifics
networks:
  hive-io:
    driver: bridge
