version: '3'
services:
  # proxy for layer 7 routing
  hive-io-proxy:
    build:
      context: ../hive-io-proxy
      args:
        PROXY_ENV: "development"
    image: hive-io-proxy
    depends_on:
      - hive-consumer-js
      - hive-consumer-js-db-viewer
      - hive-producer-js
      - hive-stream-processor-js
    expose:
      - "80"
    ports:
      - "80:80"
    volumes:
      - ../hive-io-proxy/conf/development:/usr/local/etc/haproxy:rw
    networks:
      - hive-io
    restart: on-failure

  # producers
  hive-producer-js:
    build:
      context: ../hive-producer-js
      args:
        APP_MODULE: "hive-io-domain-example"
        APP_SOURCE: "."
        NODE_ENV: "development"
    image: hive-producer-js
    environment:
      EVENT_STORE_URL: "hive-io-kafka-db:2181"
      EVENT_STORE_ID: "producer-client"
    depends_on:
      - hive-io-kafka
    command: npm run dev
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - ../hive-producer-js:/opt/app:rw
      - /opt/app/node_modules
      - ../hive-js-domain-example:/opt/app/node_modules/hive-io-domain-example:rw
      - ../hive-js:/opt/app/node_modules/hive-io-domain-example/node_modules/hive-io:rw
      - ../hive-js:/opt/app/node_modules/hive-io:rw
    networks:
      - hive-io

  # stream processors
  hive-stream-processor-js:
    build:
      context: ../hive-stream-processor-js
      args:
        APP_MODULE: "hive-io-domain-example"
        APP_SOURCE: "."
        NODE_ENV: "development"
    image: hive-stream-processor-js
    environment:
      CACHE_URL: "redis://hive-stream-processor-js-cache:6379"
      EVENT_STORE_URL: "hive-io-kafka-db:2181"
      EVENT_STORE_ID: "stream-processor-client"
    depends_on:
      - hive-stream-processor-js-cache
      - hive-io-kafka
    command: npm run dev
    expose:
      - "3000"
    ports:
      - "3001:3000"
    volumes:
      - ../hive-stream-processor-js:/opt/app:rw
      - /opt/app/node_modules
      - ../hive-js-domain-example:/opt/app/node_modules/hive-io-domain-example:rw
      - ../hive-js:/opt/app/node_modules/hive-io-domain-example/node_modules/hive-io:rw
      - ../hive-js:/opt/app/node_modules/hive-io:rw
    networks:
      - hive-io
  hive-stream-processor-js-cache:
    image: redis:4.0.8-alpine
    expose:
      - "6379"
    networks:
      - hive-io
    restart: on-failure

  # log stream containers
  hive-io-kafka:
    build:
      context: ../hive-io-kafka
      args:
        KAFKA_VERSION: "1.0.0"
        SCALA_VERSION: "2.12"
    image: hive-io-kafka
    depends_on:
      - hive-io-kafka-db
    environment:
      KAFKA_CREATE_TOPICS: "content:1:1,error:1:1,view:1:1"
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms512M"
    expose:
      - "9092"
    volumes:
      - ../hive-io-kafka/conf:/usr/local/kafka/config:rw
    networks:
      - hive-io
    restart: on-failure
  hive-io-kafka-db:
    image: zookeeper:3.4.11
    expose:
      - "2181"
    networks:
      - hive-io
    restart: on-failure

  # consumers
  hive-consumer-js:
    build:
      context: ../hive-consumer-js
      args:
        APP_MODULE: "hive-io-domain-example"
        APP_SOURCE: "."
        NODE_ENV: "development"
    image: hive-consumer-js
    environment:
      MONGO_URL: "mongodb://hive-consumer-js-db:27017/post"
      EVENT_STORE_URL: "hive-io-kafka-db:2181"
      EVENT_STORE_ID: "consumer-client"
      EVENT_STORE_OFFSET: "earliest"
    depends_on:
      - hive-consumer-js-db
      - hive-io-kafka
    command: npm run dev
    expose:
      - "3000"
    ports:
      - "3002:3000"
    volumes:
      - ../hive-consumer-js:/opt/app:rw
      - /opt/app/node_modules
      - ../hive-js-domain-example:/opt/app/node_modules/hive-io-domain-example:rw
      - ../hive-js:/opt/app/node_modules/hive-io-domain-example/node_modules/hive-io:rw
      - ../hive-js:/opt/app/node_modules/hive-io:rw
    networks:
      - hive-io
  hive-consumer-js-db:
    image: mongo:3.6.2
    expose:
      - "27017"
    networks:
      - hive-io
    restart: on-failure
  hive-consumer-js-db-viewer:
    image: mongo-express:0.44.0
    environment:
      ME_CONFIG_MONGODB_SERVER: "hive-consumer-js-db"
      ME_CONFIG_SITE_BASEURL: "/mongo/"
    depends_on:
      - hive-consumer-js-db
    expose:
      - "8081"
    ports:
      - "8081:8081"
    networks:
      - hive-io
    restart: on-failure

# networking specifics
networks:
  hive-io:
    driver: bridge
