version: '3.5'
services:
  # proxy for layer 7 routing
  hive-io-proxy:
    build:
      context: ../hive-io-proxy
      args:
        PROXY_ENV: "development"
    image: hive-io-proxy
    depends_on:
      - hive-consumer-js
      - mongo-express
      - hive-producer-js
      - hive-stream-processor-js
    ports:
      - 80:80
    volumes:
      - ../hive-io-proxy/conf/development:/usr/local/etc/haproxy:rw
    networks:
      - hive-io
    restart: on-failure

  # producers
  hive-producer-js:
    build:
      context: ../hive-producer-js
      args:
        APP_MODULE: "hive-io-domain-example"
        APP_SOURCE: "."
        NODE_ENV: "development"
    image: hive-producer-js
    environment:
      CLUSTER_SIZE: 1
      EVENT_STORE_URL: "kafka:9092"
      EVENT_STORE_ID: "producer-client"
    depends_on:
      - kafka
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - ../hive-producer-js:/opt/app:rw
      - /opt/app/node_modules
      - ../hive-js-domain-example:/opt/app/node_modules/hive-io-domain-example:rw
      - ../hive-js:/opt/app/node_modules/hive-io-domain-example/node_modules/hive-io:rw
      - ../hive-js:/opt/app/node_modules/hive-io:rw
    networks:
      - hive-io

  # stream processors
  hive-stream-processor-js:
    build:
      context: ../hive-stream-processor-js
      args:
        APP_MODULE: "hive-io-domain-example"
        APP_SOURCE: "."
        NODE_ENV: "development"
    image: hive-stream-processor-js
    environment:
      CLUSTER_SIZE: 1
      CACHE_URL: "redis://redis:6379"
      EVENT_STORE_URL: "kafka:9092"
      EVENT_STORE_ID: "stream-processor-client"
    depends_on:
      - redis
      - kafka
    command: npm run dev
    ports:
      - 3001:3000
    volumes:
      - ../hive-stream-processor-js:/opt/app:rw
      - /opt/app/node_modules
      - ../hive-js-domain-example:/opt/app/node_modules/hive-io-domain-example:rw
      - ../hive-js:/opt/app/node_modules/hive-io-domain-example/node_modules/hive-io:rw
      - ../hive-js:/opt/app/node_modules/hive-io:rw
    networks:
      - hive-io
  redis:
    image: redis:4.0.9-alpine
    networks:
      - hive-io
    restart: on-failure

  # log stream containers
  kafka:
    image: confluentinc/cp-kafka:4.1.1-1
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 9092:9092
    networks:
      - hive-io
    restart: on-failure
  zookeeper:
    image: confluentinc/cp-zookeeper:4.1.1-1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - hive-io
    restart: on-failure

  # consumers
  hive-consumer-js:
    build:
      context: ../hive-consumer-js
      args:
        APP_MODULE: "hive-io-domain-example"
        APP_SOURCE: "."
        NODE_ENV: "development"
    image: hive-consumer-js
    environment:
      CLUSTER_SIZE: 1
      MONGO_URL: "mongodb://mongo:27017/post"
      EVENT_STORE_URL: "kafka:9092"
      EVENT_STORE_ID: "consumer-client"
      EVENT_STORE_OFFSET: "earliest"
    depends_on:
      - mongo
      - kafka
    command: npm run dev
    ports:
      - 3002:3000
    volumes:
      - ../hive-consumer-js:/opt/app:rw
      - /opt/app/node_modules
      - ../hive-js-domain-example:/opt/app/node_modules/hive-io-domain-example:rw
      - ../hive-js:/opt/app/node_modules/hive-io-domain-example/node_modules/hive-io:rw
      - ../hive-js:/opt/app/node_modules/hive-io:rw
    networks:
      - hive-io
  mongo:
    image: mongo:3.6.4
    networks:
      - hive-io
    restart: on-failure
  mongo-express:
    image: mongo-express:0.45.0
    environment:
      ME_CONFIG_MONGODB_SERVER: "mongo"
      ME_CONFIG_SITE_BASEURL: "/mongo/"
    depends_on:
      - mongo
    ports:
      - 8081:8081
    networks:
      - hive-io
    restart: on-failure

# networking specifics
networks:
  hive-io:
    driver: bridge
