version: '3'
services:
  # proxy for layer 7 routing
  hive-io-proxy:
    image: fnalabs/hive-io-proxy:latest
    depends_on:
      - hive-producer-js
      - hive-consumer-js
      - hive-stream-processor-js
    expose:
      - "80"
    ports:
      - "80:80"
    networks:
      - hive-io
    restart: always

  # producers
  hive-producer-js:
    image: fnalabs/hive-producer-js:latest
    environment:
      EVENT_STORE_URL: "hive-io-kafka-db:2181"
      EVENT_STORE_ID: "producer-client"
    depends_on:
      - hive-io-kafka
    expose:
      - "3000"
    networks:
      - hive-io

  # stream processors
  hive-stream-processor-js:
    image: fnalabs/hive-stream-processor-js:latest
    environment:
      CACHE_URL: "redis://hive-stream-processor-js-cache:6379"
      EVENT_STORE_URL: "hive-io-kafka-db:2181"
      EVENT_STORE_ID: "stream-processor-client"
    depends_on:
      - hive-stream-processor-js-cache
      - hive-io-kafka
    expose:
      - "3000"
    networks:
      - hive-io
  hive-stream-processor-js-cache:
    image: redis:4.0.8-alpine
    expose:
      - "6379"
    networks:
      - hive-io
    restart: always

  # log stream containers
  hive-io-kafka:
    image: fnalabs/hive-io-kafka:latest
    depends_on:
      - hive-io-kafka-db
    environment:
      KAFKA_CREATE_TOPICS: "content:1:1,error:1:1,view:1:1"
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms512M"
    expose:
      - "9092"
    networks:
      - hive-io
    restart: always
  hive-io-kafka-db:
    image: zookeeper:3.4.11
    expose:
      - "2181"
    networks:
      - hive-io
    restart: always

  # consumers
  hive-consumer-js:
    image: fnalabs/hive-consumer-js:latest
    environment:
      MONGO_URL: "mongodb://hive-consumer-js-db:27017/post"
      EVENT_STORE_URL: "hive-io-kafka-db:2181"
      EVENT_STORE_ID: "consumer-client"
    depends_on:
      - hive-consumer-js-db
      - hive-io-kafka
    expose:
      - "3000"
    networks:
      - hive-io
  hive-consumer-js-db:
    image: mongo:3.6.2
    expose:
      - "27017"
    networks:
      - hive-io
    restart: always

# networking specifics
networks:
  hive-io:
    driver: bridge
