version: '3'
services:
  # proxy for layer 7 routing
  js-cqrs-es-proxy:
    build:
      context: ../js-cqrs-es-proxy
      args:
        PROXY_ENV: "development"
    image: js-cqrs-es-proxy
    depends_on:
      - docker-nodejs-producer-starter
      - docker-nodejs-consumer-starter
      - docker-nodejs-stream-processor-starter
    expose:
      - "80"
    ports:
      - "80:80"
    volumes:
      - ../js-cqrs-es-proxy/conf/development:/usr/local/etc/haproxy:rw
    networks:
      - js-cqrs-es
    restart: always

  # producers
  docker-nodejs-producer-starter:
    image: aeilers/docker-nodejs-producer:latest
    environment:
      EVENT_STORE_URL: "docker-kafka-db:2181"
      EVENT_STORE_ID: "producer-client"
    depends_on:
      - docker-kafka
    expose:
      - "3000"
    networks:
      - js-cqrs-es

  # stream processors
  docker-nodejs-stream-processor-starter:
    image: aeilers/docker-nodejs-stream-processor:latest
    environment:
      CACHE_URL: "redis://js-cqrs-es-cache:6379"
      EVENT_STORE_URL: "docker-kafka-db:2181"
      EVENT_STORE_ID: "stream-processor-client"
    depends_on:
      - js-cqrs-es-cache
      - docker-kafka
    expose:
      - "3000"
    networks:
      - js-cqrs-es

  # stream processor cache
  js-cqrs-es-cache:
    image: redis:3.2.8-alpine
    expose:
      - "6379"
    networks:
      - js-cqrs-es
    restart: always

  # log stream containers
  docker-kafka:
    image: aeilers/docker-kafka:latest
    depends_on:
      - docker-kafka-db
    environment:
      KAFKA_CREATE_TOPICS: "content:1:1,error:1:1,view:1:1"
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms512M"
    expose:
      - "9092"
    networks:
      - js-cqrs-es
    restart: always
  docker-kafka-db:
    image: zookeeper:3.4.10
    expose:
      - "2181"
    networks:
      - js-cqrs-es
    restart: always

  # consumers
  docker-nodejs-consumer-starter:
    image: aeilers/docker-nodejs-consumer:latest
    environment:
      MONGO_URL: "mongodb://docker-nodejs-consumer-starter-db:27017/post"
      EVENT_STORE_URL: "docker-kafka-db:2181"
      EVENT_STORE_ID: "consumer-client"
    depends_on:
      - docker-nodejs-consumer-starter-db
      - docker-kafka
    expose:
      - "3000"
    networks:
      - js-cqrs-es
  docker-nodejs-consumer-starter-db:
    image: mongo:3.4.4
    expose:
      - "27017"
    networks:
      - js-cqrs-es
    restart: always

# networking specifics
networks:
  js-cqrs-es:
    driver: bridge
